---
# Software Versions & URLs
node_exporter_version: "1.11.1"
node_exporter_checksum: "sha256:8d73447c47488a94f7eba467838c815ea7dceb449c75b1b8e91fa6dc3e0e364e"
prometheus_version: "3.11.3"
prometheus_checksum: "sha256:bd6978937d64f4afa82919e0c4b3b83ace50808b953ab6174e480ca7dda2ba9a"
crictl_version: "v1.35.0"
cni_plugins_version: "v1.4.0"
kubernetes_version: "1.35.0"
kubernetes_gitlab_artifacts_url: "https://gitlab.com/riseproject/risc-v-runner/kubernetes/-/jobs/13257210986/artifacts/download"

# Kernel & Module Configuration
kernel_version_suffix: "-scw1"
modules_to_build:
  - net/netfilter/ipset
  - fs/erofs
  - drivers/md

modules_to_load_k8s:
  - overlay
  - br_netfilter
  - nf_conntrack
  - tun

modules_to_load_users:
  - ip_set
  - ip_set_bitmap_ip
  - ip_set_bitmap_ipmac
  - ip_set_bitmap_port
  - ip_set_hash_ip
  - ip_set_hash_ipmac
  - ip_set_hash_ipmark
  - ip_set_hash_ipport
  - ip_set_hash_ipportip
  - ip_set_hash_ipportnet
  - ip_set_hash_mac
  - ip_set_hash_net
  - ip_set_hash_netiface
  - ip_set_hash_netnet
  - ip_set_hash_netport
  - ip_set_hash_netportnet
  - ip_set_list_set
  - erofs
  - dm_verity

# Cockpit & Probe Configuration
cockpit_metrics_push_url: ""
cockpit_metrics_token: ""
github_probe_token: ""
